[general]
site = 'lab'
nodename = 'sd-eng1'
device = 'workstation'
directory = '/home/arl203/icebear/telemetry/'
user = ''

[daemon]
[daemon.service]


[scripts]
[scripts.test]
entry = 'src.scripts.test.test_script'
schedule = 1

[scripts.inxi]
entry = 'src.scripts.inxi.inxi_cli'
schedule = 10

#[scripts.camera]
#[webcam.1]
#camera = 0
#rotate = 0
#scale = 100
#mirror = -1
#contrast = 0
#brightness = 255
#schedule = []



